"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-04 00:29:23.084850
"""

import sqlalchemy as sa
from alembic import op

import tradingagent.storage.types

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("occurred_at", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_occurred_at"), ["occurred_at"], unique=False)

    op.create_table(
        "candles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column(
            "timeframe",
            sa.Enum(
                "M1",
                "M5",
                "M15",
                "M30",
                "H1",
                "H4",
                "D1",
                name="timeframe",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("open_time", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.Column("open", sa.Double(), nullable=False),
        sa.Column("high", sa.Double(), nullable=False),
        sa.Column("low", sa.Double(), nullable=False),
        sa.Column("close", sa.Double(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("ingested_at", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "timeframe IN ('M1', 'M5', 'M15', 'M30', 'H1', 'H4', 'D1')",
            name=op.f("ck_candles_timeframe"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candles")),
        sa.UniqueConstraint(
            "symbol", "timeframe", "open_time", name=op.f("uq_candles_symbol_timeframe_open_time")
        ),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=16), nullable=False),
        sa.Column("window_start", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.Column("window_end", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("generated_at", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.Column("sent_at", tradingagent.storage.types.UtcDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint("period", "window_start", name=op.f("uq_reports_period_window_start")),
    )
    op.create_table(
        "strategy_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ref", sa.String(length=80), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("first_seen_at", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_versions")),
        sa.UniqueConstraint("ref", name=op.f("uq_strategy_versions_ref")),
    )
    op.create_table(
        "system_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "info",
                "warning",
                "critical",
                name="severity",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("occurred_at", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'critical')", name=op.f("ck_system_events_severity")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_events")),
    )
    with op.batch_alter_table("system_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_system_events_occurred_at"), ["occurred_at"], unique=False
        )

    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("strategy_version_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column(
            "timeframe",
            sa.Enum(
                "M1",
                "M5",
                "M15",
                "M30",
                "H1",
                "H4",
                "D1",
                name="timeframe",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "direction",
            sa.Enum(
                "BUY",
                "SELL",
                name="direction",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "mode",
            sa.Enum(
                "OBSERVATION",
                "SIGNAL",
                "PAPER",
                "DEMO",
                "LIVE",
                name="tradingmode",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("observed_price", sa.Double(), nullable=False),
        sa.Column("entry_low", sa.Double(), nullable=False),
        sa.Column("entry_high", sa.Double(), nullable=False),
        sa.Column("stop_loss", sa.Double(), nullable=False),
        sa.Column("take_profits", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("indicators", sa.JSON(), nullable=False),
        sa.Column("generated_at", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.Column("expires_at", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "candidate",
                "risk_rejected",
                "validated",
                "sent",
                "expired",
                "accepted",
                "ignored",
                "order_sent",
                "order_accepted",
                "order_rejected",
                "position_open",
                "partially_closed",
                "closed",
                "cancelled",
                "error",
                name="signalstate",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.CheckConstraint("direction IN ('BUY', 'SELL')", name=op.f("ck_signals_direction")),
        sa.CheckConstraint(
            "mode IN ('OBSERVATION', 'SIGNAL', 'PAPER', 'DEMO', 'LIVE')",
            name=op.f("ck_signals_tradingmode"),
        ),
        sa.CheckConstraint(
            "state IN ('candidate', 'risk_rejected', 'validated', 'sent', 'expired', 'accepted', 'ignored', 'order_sent', 'order_accepted', 'order_rejected', 'position_open', 'partially_closed', 'closed', 'cancelled', 'error')",
            name=op.f("ck_signals_signalstate"),
        ),
        sa.CheckConstraint(
            "timeframe IN ('M1', 'M5', 'M15', 'M30', 'H1', 'H4', 'D1')",
            name=op.f("ck_signals_timeframe"),
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_versions.id"],
            name=op.f("fk_signals_strategy_version_id_strategy_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_signals_idempotency_key")),
    )
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.create_index(
            "ix_signals_symbol_generated_at", ["symbol", "generated_at"], unique=False
        )

    op.create_table(
        "ai_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=True),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column(
            "ai_filter",
            sa.Enum(
                "shadow",
                "advisory",
                "required",
                name="aifilter",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=True),
        sa.Column("verdict", sa.String(length=16), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("cost_eur", tradingagent.storage.types.ExactDecimal(length=48), nullable=True),
        sa.Column("called_at", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "ai_filter IN ('shadow', 'advisory', 'required')", name=op.f("ck_ai_calls_aifilter")
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"], ["signals.id"], name=op.f("fk_ai_calls_signal_id_signals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_calls")),
    )
    with op.batch_alter_table("ai_calls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_calls_signal_id"), ["signal_id"], unique=False)

    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "BUY",
                "SELL",
                name="direction",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("volume", tradingagent.storage.types.ExactDecimal(length=48), nullable=False),
        sa.Column("requested_price", sa.Double(), nullable=False),
        sa.Column("stop_loss", sa.Double(), nullable=False),
        sa.Column("take_profit", sa.Double(), nullable=True),
        sa.Column(
            "mode",
            sa.Enum(
                "OBSERVATION",
                "SIGNAL",
                "PAPER",
                "DEMO",
                "LIVE",
                name="tradingmode",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "sent",
                "accepted",
                "rejected",
                "filled",
                "cancelled",
                "error",
                name="orderstate",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("broker_order_ticket", sa.BigInteger(), nullable=True),
        sa.Column("retcode", sa.Integer(), nullable=True),
        sa.Column("broker_comment", sa.String(length=255), nullable=True),
        sa.Column("created_at", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.Column("updated_at", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.CheckConstraint("direction IN ('BUY', 'SELL')", name=op.f("ck_orders_direction")),
        sa.CheckConstraint(
            "mode IN ('OBSERVATION', 'SIGNAL', 'PAPER', 'DEMO', 'LIVE')",
            name=op.f("ck_orders_tradingmode"),
        ),
        sa.CheckConstraint(
            "state IN ('sent', 'accepted', 'rejected', 'filled', 'cancelled', 'error')",
            name=op.f("ck_orders_orderstate"),
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"], ["signals.id"], name=op.f("fk_orders_signal_id_signals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("broker_order_ticket", name=op.f("uq_orders_broker_order_ticket")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_orders_idempotency_key")),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_orders_signal_id"), ["signal_id"], unique=False)

    op.create_table(
        "risk_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "authorized",
                "reduced",
                "refused",
                name="riskoutcome",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("checks", sa.JSON(), nullable=False),
        sa.Column("volume", tradingagent.storage.types.ExactDecimal(length=48), nullable=True),
        sa.Column("risk_eur", tradingagent.storage.types.ExactDecimal(length=48), nullable=True),
        sa.Column("margin_eur", tradingagent.storage.types.ExactDecimal(length=48), nullable=True),
        sa.Column("decided_at", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('authorized', 'reduced', 'refused')",
            name=op.f("ck_risk_decisions_riskoutcome"),
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"], ["signals.id"], name=op.f("fk_risk_decisions_signal_id_signals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_decisions")),
    )
    with op.batch_alter_table("risk_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_risk_decisions_signal_id"), ["signal_id"], unique=False
        )

    op.create_table(
        "signal_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "candidate",
                "risk_rejected",
                "validated",
                "sent",
                "expired",
                "accepted",
                "ignored",
                "order_sent",
                "order_accepted",
                "order_rejected",
                "position_open",
                "partially_closed",
                "closed",
                "cancelled",
                "error",
                name="signalstate",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "state IN ('candidate', 'risk_rejected', 'validated', 'sent', 'expired', 'accepted', 'ignored', 'order_sent', 'order_accepted', 'order_rejected', 'position_open', 'partially_closed', 'closed', 'cancelled', 'error')",
            name=op.f("ck_signal_events_signalstate"),
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"], ["signals.id"], name=op.f("fk_signal_events_signal_id_signals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal_events")),
    )
    with op.batch_alter_table("signal_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_signal_events_signal_id"), ["signal_id"], unique=False)

    op.create_table(
        "executions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("broker_deal_ticket", sa.BigInteger(), nullable=False),
        sa.Column("price", sa.Double(), nullable=False),
        sa.Column("volume", tradingagent.storage.types.ExactDecimal(length=48), nullable=False),
        sa.Column("slippage", sa.Double(), nullable=True),
        sa.Column("executed_at", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_executions_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executions")),
        sa.UniqueConstraint("broker_deal_ticket", name=op.f("uq_executions_broker_deal_ticket")),
    )
    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_executions_order_id"), ["order_id"], unique=False)

    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("broker_position_ticket", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "BUY",
                "SELL",
                name="direction",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("volume", tradingagent.storage.types.ExactDecimal(length=48), nullable=False),
        sa.Column("open_price", sa.Double(), nullable=False),
        sa.Column("stop_loss", sa.Double(), nullable=False),
        sa.Column("take_profit", sa.Double(), nullable=True),
        sa.Column(
            "mode",
            sa.Enum(
                "OBSERVATION",
                "SIGNAL",
                "PAPER",
                "DEMO",
                "LIVE",
                name="tradingmode",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "open",
                "closed",
                name="positionstate",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("opened_at", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.Column("updated_at", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.CheckConstraint("direction IN ('BUY', 'SELL')", name=op.f("ck_positions_direction")),
        sa.CheckConstraint(
            "mode IN ('OBSERVATION', 'SIGNAL', 'PAPER', 'DEMO', 'LIVE')",
            name=op.f("ck_positions_tradingmode"),
        ),
        sa.CheckConstraint("state IN ('open', 'closed')", name=op.f("ck_positions_positionstate")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_positions_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
        sa.UniqueConstraint(
            "broker_position_ticket", name=op.f("uq_positions_broker_position_ticket")
        ),
    )
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_positions_order_id"), ["order_id"], unique=False)

    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum(
                "OBSERVATION",
                "SIGNAL",
                "PAPER",
                "DEMO",
                "LIVE",
                name="tradingmode",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("closed_at", tradingagent.storage.types.UtcDateTime(), nullable=False),
        sa.Column("close_price", sa.Double(), nullable=False),
        sa.Column("pnl_eur", tradingagent.storage.types.ExactDecimal(length=48), nullable=False),
        sa.Column("risk_eur", tradingagent.storage.types.ExactDecimal(length=48), nullable=False),
        sa.Column("exit_reason", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "mode IN ('OBSERVATION', 'SIGNAL', 'PAPER', 'DEMO', 'LIVE')",
            name=op.f("ck_trades_tradingmode"),
        ),
        sa.ForeignKeyConstraint(
            ["position_id"], ["positions.id"], name=op.f("fk_trades_position_id_positions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades")),
        sa.UniqueConstraint("position_id", name=op.f("uq_trades_position_id")),
    )
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trades_closed_at"), ["closed_at"], unique=False)

    # ### end Alembic commands ###
    _create_append_only_triggers()


APPEND_ONLY_TABLES = ("signal_events", "executions", "trades", "audit_log")
ALL_TABLES = (
    "audit_log",
    "candles",
    "reports",
    "strategy_versions",
    "system_events",
    "signals",
    "ai_calls",
    "orders",
    "risk_decisions",
    "signal_events",
    "executions",
    "positions",
    "trades",
)


def _dialect() -> str:
    dialect = op.get_bind().dialect.name
    if dialect not in ("sqlite", "postgresql"):
        # Fail loudly rather than silently skip immutability on another database.
        raise NotImplementedError(f"append-only triggers not written for {dialect}")
    return dialect


def _create_append_only_triggers() -> None:
    if _dialect() == "sqlite":
        for table in APPEND_ONLY_TABLES:
            for event in ("UPDATE", "DELETE"):
                op.execute(
                    f"CREATE TRIGGER {table}_no_{event.lower()} BEFORE {event} ON {table} "
                    f"BEGIN SELECT RAISE(ABORT, '{table} is append-only'); END"
                )
        return
    op.execute(
        "CREATE FUNCTION forbid_append_only_change() RETURNS trigger LANGUAGE plpgsql AS $$ "
        "BEGIN RAISE EXCEPTION '% is append-only', TG_TABLE_NAME; END $$"
    )
    for table in APPEND_ONLY_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_no_change BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_append_only_change()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION forbid_append_only_change()"
        )
    # Supabase serves the public schema over a web API keyed by a public key. RLS with no
    # policy denies that API everything; the agent connects as table owner and bypasses it.
    for table in (*ALL_TABLES, "alembic_version"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")


def _drop_append_only_triggers() -> None:
    if _dialect() == "sqlite":
        for table in APPEND_ONLY_TABLES:
            for event in ("update", "delete"):
                op.execute(f"DROP TRIGGER IF EXISTS {table}_no_{event}")
        return
    for table in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_change ON {table}")
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_truncate ON {table}")
    op.execute("DROP FUNCTION IF EXISTS forbid_append_only_change()")


def downgrade() -> None:
    _drop_append_only_triggers()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trades_closed_at"))

    op.drop_table("trades")
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_positions_order_id"))

    op.drop_table("positions")
    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_executions_order_id"))

    op.drop_table("executions")
    with op.batch_alter_table("signal_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_signal_events_signal_id"))

    op.drop_table("signal_events")
    with op.batch_alter_table("risk_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_decisions_signal_id"))

    op.drop_table("risk_decisions")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orders_signal_id"))

    op.drop_table("orders")
    with op.batch_alter_table("ai_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_calls_signal_id"))

    op.drop_table("ai_calls")
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.drop_index("ix_signals_symbol_generated_at")

    op.drop_table("signals")
    with op.batch_alter_table("system_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_system_events_occurred_at"))

    op.drop_table("system_events")
    op.drop_table("strategy_versions")
    op.drop_table("reports")
    op.drop_table("candles")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_occurred_at"))

    op.drop_table("audit_log")
    # ### end Alembic commands ###
