"""Strategy research tools (F-025, TASK-063 to TASK-065).

Never loaded in production, exactly like `tradingagent.backtest`: the anti-overfitting
protocol, the per-market campaigns and the promotion thresholds live here, away from the
agent that trades.
"""

from tradingagent.research.campaign import (
    CampaignReport,
    CandidateReport,
    CandidateSpec,
    CorrelationPair,
    MarketReport,
    correlate_markets,
    pearson,
    rank_candidates,
    run_campaign,
)
from tradingagent.research.promotion import (
    AcceptanceThresholds,
    ManifestSpec,
    PromotionDecision,
    PromotionError,
    PromotionEvidence,
    PromotionOutcome,
    ThresholdsChangedError,
    evaluate_promotion,
    evidence_from_campaign,
    load_thresholds,
    promote,
    record_decision,
    write_manifest,
    write_thresholds,
)
from tradingagent.research.protocol import (
    CandidateScore,
    DataSplit,
    Fold,
    MonteCarloReport,
    OptimizationResult,
    RegimeResult,
    SealedAccessError,
    SealedSet,
    StabilityReport,
    WalkForwardPlan,
    confirm,
    monte_carlo,
    optimize,
    parameter_dispersion,
    period_report,
    perturb_parameters,
    profitable_regime_ratio,
    robustness_score,
    split_dataset,
    stability_report,
    walk_forward,
)

__all__ = [
    "AcceptanceThresholds",
    "CampaignReport",
    "CandidateReport",
    "CandidateScore",
    "CandidateSpec",
    "CorrelationPair",
    "DataSplit",
    "Fold",
    "ManifestSpec",
    "MarketReport",
    "MonteCarloReport",
    "OptimizationResult",
    "PromotionDecision",
    "PromotionError",
    "PromotionEvidence",
    "PromotionOutcome",
    "RegimeResult",
    "SealedAccessError",
    "SealedSet",
    "StabilityReport",
    "ThresholdsChangedError",
    "WalkForwardPlan",
    "confirm",
    "correlate_markets",
    "evaluate_promotion",
    "evidence_from_campaign",
    "load_thresholds",
    "monte_carlo",
    "optimize",
    "parameter_dispersion",
    "pearson",
    "period_report",
    "perturb_parameters",
    "profitable_regime_ratio",
    "promote",
    "rank_candidates",
    "record_decision",
    "robustness_score",
    "run_campaign",
    "split_dataset",
    "stability_report",
    "walk_forward",
    "write_manifest",
    "write_thresholds",
]
